# Generated by Django 3.1.4 on 2020-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=5)),
            ],
        ),
    ]
